travis:
  secure:
    BINSTAR_TOKEN: EqT3g8Zd6GbzCWken3WqjLf5nvyY30UxGxE+8Z2WhZ2xHmqiUmad9W6/0O2Bx7/5aaP0MgKdyPSy/4Pn58d606vJl9oLmZFYYKVWqnVirM+k74RlXHsDdvOU+S7AUDlV4kgJkKc/FXy0OHl+HiTaOy43klRRlpJ0ttc54JBr6KRKuDbxSElCjDU5WDhkV5UEiV323vBww8RI74s6hS2eDJB+KjY6emLP2Z2yLXhIDoolcHx/YHTjTIPudU4AmVr5Y0vkpaXDzU2aXbqA3cOLN1Y3LpHrQhu0uq6qUCfSF5oVrPxoqGh/veZU+emkB+pf/DOtIryQFtDyoUyaJDnRBtyaUuerIrNFMbL8bbDlvfgzIgDiyGosX7TF3OZWqLmZFR+q+ry3PhPdzgOh1D3uzh5IFBu5tIfcs5VTMNzEkUJGZ1vF+L92Q0YRVhjKGyVUkrvpZDwakflWoJFUzfb2INPTH/Yew5Jm3cbWsnpqY4cyelIZEsxV0Q8VJqhU4jvFD/R27uGhQj4AYAJat8Dv40UnAn8gntnjz76lFQPqI0L2ErXP01kbn451fPo9qcjIWeCJSpALjP02WWnz6SALpsfiBAlCJKpsRFe+FjJWA/i6X+EAb5p25XaVlon4fvDpw55i0iQlXM5EsG/89+mLl35/iagVGONNtxJkkyATZPw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
